version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
